name: Update Docker Hub Description

on: 
    workflow_dispatch:
    push:
        branches:
        - main
      
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/discord-linuxserver
        short-description: ${{ github.event.repository.description }}
